name: Bug Report
description: Report a problem in xLaDe
title: '[BUG]: '
labels:
  - bug
body:
  - type: textarea
    id: problem
    attributes:
      label: Bug:
      description: Describe the problem clearly
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run ...
        2. Run ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Ideal behaviour
      description: Explain the expected behaviour
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Include the versions used.
      placeholder: |
        xLaDe version:
        Python version:
        Lean version:
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and additional information
      description: Paste relevant error messages or logs here.
