name: Feature Request
description: Suggest an improvement for xLaDe
title: "[FEATURE]: "
labels:
  - enhancement
body:
  - type: textarea
    id: idea
    attributes:
      label: Feature
      description: What do you want us to improve?
    validations:
      required: true

  - type: textarea
    id: reason
    attributes:
      label: Use
      description: Explain the use of feature
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Miscellaneous
      description: Additional info or comments
    validations:
      reuired: false
