name: xLaDe Issue
description: Helps in creating an issue easily
title: "[Issue Type]: "
labels: []
assignees: []

body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      placeholder: |
        Please tell the issue you have
        (Don't tell non-xLaDe issues. We may not be able to help you)
    validations:
      required: true

  - type: dropdown
    id: issue-type
    attributes:
      label: Type of Issue
      options:
        - Bug                     [bug]
        - Feature Request         [feat]
        - Documentation           [doc]
        - Infrastructure          [inf]
        - Ecosystem level         [eco]
        - Other                   [other]
    validations:
      required: true

  - type: input
    id: xlade-version
    attributes:
      label: Affected Version(s)
      placeholder: x.y.z
    validations:
      required: true

  - type: input
    id: other-environment
    attributes:
      label: Environment
      placeholder: Names and versions of other relevant tools, if applicable.
    validations:
      required: false

  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      placeholder: Please paste the issue reproduction steps, expected outcome, logs, or any useful info if applicable.
    validations:
      required: false

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      placeholder: Anything else you would like to comment.
    validations:
      required: false