CREATE TABLE IF NOT EXISTS error_rules (
  phrase TEXT PRIMARY KEY,
  explanation TEXT NOT NULL
);

INSERT OR IGNORE INTO error_rules (phrase, explanation) VALUES
  ('unknown identifier', 'Lean cannot find this name. Check its spelling, scope, and imports.'),
  ('type mismatch', 'The value has a different type from the type Lean expected.'),
  ('application type mismatch', 'An argument does not have the type required by this function.'),
  ('failed to synthesize instance', 'Lean could not find a required typeclass instance. Check imports or add the instance explicitly.'),
  ('invalid field', 'This field is not available on the value. Check the value''s type and the field name.'),
  ('unsolved goals', 'Lean still has proof goals left. Add a tactic or term that proves each goal.'),
  ('unexpected token', 'Lean found syntax it did not expect. Check the nearby punctuation and structure.'),
  ('unexpected identifier', 'Lean found a name in a place where another kind of syntax was expected.'),
  ('unexpected end of input', 'Lean reached the end of the file before the declaration or expression was complete.'),
  ('invalid syntax', 'The expression does not follow Lean''s syntax. Check nearby delimiters and keywords.'),
  ('unexpected command', 'This command is not valid at the current position in the file.'),
  ('unknown constant', 'Lean cannot find this declaration. Check its module import and spelling.'),
  ('unknown namespace', 'This namespace is unavailable. Check the namespace name and its imports.'),
  ('unknown option', 'Lean does not recognise this option. Check the option name and Lean version.'),
  ('declaration has metavariables', 'Lean could not infer every part of this declaration. Add explicit types or arguments.'),
  ('declaration uses ''sorry''', 'The declaration contains an unfinished proof. Replace `sorry` with a proof term or tactic block.'),
  ('declaration uses ''admit''', 'The declaration contains an admitted proof. Complete the proof before relying on it.'),
  ('failed to infer', 'Lean could not infer a type, argument, or implicit parameter. Add an annotation or make the argument explicit.'),
  ('failed to synthesize', 'Lean needs an instance or type information that is not available at this point.'),
  ('cannot synthesize placeholder', 'A placeholder `_` has no type information. Replace it with a value or add a type annotation.'),
  ('invalid argument name', 'The named argument does not exist for this function. Check the declaration and argument spelling.'),
  ('function expected at', 'Lean expected a function but found a value. Check the expression before the arguments.'),
  ('function expected', 'Lean expected a function in this application. Check the type of the expression being called.'),
  ('invalid function value', 'This expression cannot be used as a function. Check its type and the number of arguments.'),
  ('invalid coercion', 'Lean cannot convert this value to the expected type. Add a valid conversion or change the type.'),
  ('failed to find a coercion', 'Lean found no automatic conversion between these types. Use an explicit conversion.'),
  ('ambiguous', 'More than one declaration or interpretation matches. Add a type, namespace, or argument annotation.'),
  ('ambiguous overload', 'Several overloaded declarations match this expression. Qualify the name or add type information.'),
  ('invalid field notation', 'Field notation does not apply to this value. Check the receiver type and field name.'),
  ('invalid projection', 'This projection cannot be used with the given structure value. Check the structure type.'),
  ('invalid constructor', 'The constructor does not belong to the expected inductive type.'),
  ('unknown constructor', 'Lean cannot find this constructor. Check the inductive type and its namespace.'),
  ('missing cases', 'The pattern match does not cover every constructor. Add the missing cases or a catch-all pattern.'),
  ('inaccessible pattern', 'This pattern cannot match the value available in the current branch.'),
  ('tactic ''exact'' failed', 'The proposed proof has the wrong type for the current goal.'),
  ('tactic ''apply'' failed', 'The theorem cannot be applied to this goal. Check its conclusion and required premises.'),
  ('tactic ''rfl'' failed', 'The two sides are not definitionally equal. Try rewriting or provide a different proof.'),
  ('tactic ''simp'' failed', 'The simplifier could not close the goal. Inspect the remaining goal and add a useful lemma.'),
  ('no goals to be solved', 'A tactic was run after the proof was already complete. Remove the extra tactic.'),
  ('unsolved goals', 'Lean still has proof goals left. Add a tactic or term that proves each goal.'),
  ('declaration uses ''sorryAx''', 'The declaration relies on an unfinished proof axiom. Replace it with a complete proof.'),
  ('fail to show termination', 'Lean could not prove that this recursive definition terminates. Add a termination argument or use a structurally recursive definition.'),
  ('fail to show decreasing argument', 'Lean could not find a recursive argument that becomes smaller. Mark the decreasing argument or restructure the recursion.'),
  ('recursive declaration has not been compiled', 'The recursive declaration failed its termination or type checks and cannot be used yet.'),
  ('invalid `where` declaration', 'The local declaration after `where` has invalid syntax or does not fit the enclosing definition.'),
  ('invalid binder annotation', 'The binder type annotation is malformed. Check parentheses, colons, and binder names.'),
  ('invalid pattern', 'This pattern does not match the shape of the value being analysed.'),
  ('invalid `do` notation', 'The do-block contains an expression or bind that does not fit the expected monadic type.'),
  ('failed to compile', 'Lean could not compile this declaration. Read the preceding diagnostics for the first reported cause.'),
  ('module name is not valid', 'The module name does not match Lean''s module naming rules or file layout.'),
  ('declaration already has been declared', 'A declaration with this name already exists. Rename it or place it in another namespace.'),
  ('already declared', 'A declaration with this name already exists. Rename it or use a different namespace.'),
  ('invalid import', 'Lean cannot load this import. Check the module name, file path, and project dependencies.'),
  ('unknown package', 'The requested package is unavailable. Check the Lake dependencies and package name.'),
  ('resulting type of constructor', 'A constructor produced a type different from the inductive type being declared.'),
  ('depends on noncomputable', 'This declaration uses noncomputable definitions. Mark it `noncomputable` or use computable definitions.'),
  ('induction pattern with', 'The induction pattern or `with` clause has a form Lean cannot elaborate. Check the induction syntax.'),
  ('invalid parameter', 'A constructor uses an inductive parameter with the wrong value or type.'),
  ('parameter not present', 'A constructor refers to an inductive parameter that is missing from the surrounding declaration.'),
  ('type of a binder could not be inferred', 'Lean cannot determine the type of this binder. Add an explicit type annotation.'),
  ('type of a definition could not be inferred', 'Lean cannot determine the type of this definition. Add a result type or clarify its value.'),
  ('invalid dotted identifier', 'Dotted notation cannot be resolved from the expected type. Qualify the name or add type information.'),
  ('tried to project data from a proof', 'A proof contains propositions and cannot provide data through this projection.'),
  ('eliminate a proof into a higher type universe', 'This proof elimination would produce data in a universe that Lean does not permit.'),
  ('match alternative will never be reached', 'An earlier match pattern already covers this case. Remove or reorder the redundant alternative.'),
  ('declaration has free variables', 'The declaration refers to local variables that are not included in its parameters.'),
  ('unknown metavariable', 'Lean cannot find this temporary metavariable. Check the tactic state and the scope of the placeholder.'),
  ('invalid universe level', 'The universe level is malformed or used where a different level is required.'),
  ('universe level is not a parameter', 'This universe name was used as a parameter without being declared.'),
  ('invalid let declaration', 'The `let` declaration has an invalid name, type, value, or body.'),
  ('invalid binder', 'The binder syntax or binder type is invalid. Check names, annotations, and parentheses.'),
  ('unused variable', 'This variable is declared but never used. Remove it or check whether the declaration is incomplete.'),
  ('declaration uses ''unsafe''', 'This declaration depends on unsafe code and cannot be used in a theorem or safe definition.'),
  ('cannot evaluate code because', 'Lean cannot evaluate this expression in the requested context. Check executability and required instances.'),
  ('failed to compile definition', 'The definition could not be compiled. Inspect the first error in the declaration.'),
  ('invalid alternative', 'This match alternative has an invalid pattern or result expression.'),
  ('invalid discriminant', 'The match discriminant has an invalid type or does not support the requested pattern matching.'),
  ('failed to elaborate match expression', 'Lean could not determine the match structure. Check discriminants, patterns, and branch result types.'),
  ('motive is not type correct', 'The match or eliminator motive has the wrong type. Make the expected result depend on the discriminants correctly.'),
  ('recursor can only eliminate', 'This recursor has a restricted elimination target. Use a proposition-compatible result or a different eliminator.'),
  ('invalid recursor', 'The requested recursor does not apply to this inductive type or elimination target.'),
  ('failed to prove', 'Lean could not prove the required side condition. Inspect the generated goal and provide a supporting lemma.'),
  ('maximum heartbeats', 'Lean stopped after reaching its computation limit. Simplify the proof or raise the relevant heartbeat option.'),
  ('maximum recursion depth', 'Lean reached its recursion-depth limit. Simplify nested definitions or raise the recursion-depth option.'),
  ('deterministic timeout', 'Lean stopped because the deterministic timeout was reached. Reduce the computation or adjust the timeout.'),
  ('simp made no progress', 'The simplifier changed nothing. Check the goal and add a rewrite rule that applies.'),
  ('no applicable extensionality theorem', 'The `ext` tactic found no suitable extensionality theorem for the current goal.'),
  ('tactic ''intro'' failed', 'The goal is not a function or forall proposition, so there is nothing to introduce.'),
  ('tactic ''constructor'' failed', 'The goal has no constructor that can be selected by this tactic.'),
  ('tactic ''cases'' failed', 'This value cannot be split with `cases` in the current context.'),
  ('tactic ''induction'' failed', 'The selected expression cannot be used for induction with the current goal.'),
  ('tactic ''rw'' failed', 'The rewrite rule does not match the target or hypotheses at this location.'),
  ('tactic ''change'' failed', 'The new target is not definitionally equal to the current target.'),
  ('tactic ''assumption'' failed', 'No local hypothesis has the type required by the current goal.'),
  ('tactic ''decide'' failed', 'Lean could not compute a decision for this proposition. Check its Decidable instance.'),
  ('tactic ''omega'' failed', 'The arithmetic goal is outside the fragment handled by `omega`, or needs a preparatory rewrite.'),
  ('tactic ''simp'' failed', 'The simplifier could not close the goal. Inspect the remaining goal and add a useful lemma.'),
  ('invalid tactic', 'Lean does not recognise this tactic in the current environment. Check its spelling and imports.'),
  ('unexpected end of syntax', 'A syntax construct is incomplete. Add the missing closing delimiter, branch, or expression.'),
  ('ambiguous namespace', 'More than one namespace interpretation is available. Use a fully qualified name.'),
  ('invalid option value', 'The option exists but its value has the wrong format or type.'),
  ('option has already been set', 'This option was configured more than once in a conflicting way. Keep one consistent setting.');
